In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_csv('play_tennis.csv')

In [3]:
df.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [4]:
df = df.drop(columns=['day'])

In [5]:
df

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [7]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [8]:
py = 9/14
pn = 5/14

In [9]:
py,pn

(0.6428571428571429, 0.35714285714285715)

In [ ]:
pd.crosstab(df['outlook'],df['play']) #Outlook

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [12]:
Pon = 0   # P of overcast on no 
Prn = 2/5 # P of rain on No 
Psn = 3/5 # P of sunny on No 

Poy=4/9 # P of overcast on Yes 
Pry=3/9 # P of rain on Yes
Psy=2/9 # P of sunny on Yes

In [13]:
pd.crosstab(df['temp'],df['play']) # Temperature

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [14]:
P_Cool_No = 1/5
P_Hot_No = 2/5 
P_Mild_No = 2/5 

P_Cool_Yes = 3/9
P_Hot_Yes = 2/9
P_Mild_Yes = 4/9

In [16]:
pd.crosstab(df['humidity'],df['play']) # Humidity

play      No  Yes
humidity
High       4    3
Normal     1    6

In [17]:
P_High_No = 4/5
P_Normal_NO = 1/5 

P_High_Yes = 3/9
P_Normal_Yes = 6/9

In [18]:
pd.crosstab(df['wind'],df['play']) # Wind

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [22]:
P_Strong_NO = 3/5
P_Weak_NO = 2/5

P_Strong_YES = 3/9
P_Weak_YES = 6/9

In [23]:
# find For {sunny,hot,high,weak}

Pyes = py*Psy*P_High_Yes*P_Hot_Yes*P_Weak_YES
Pyes

0.007054673721340388

In [26]:
Pno= py*Psn*P_High_No*P_Hot_No*P_Weak_NO
Pno

0.04937142857142858

In [ ]:
Pno > Pyes # NO play

True